---
# Ansible Galaxy dependencies
#
# Install with:
#   ansible-galaxy collection install -r requirements.yml

collections:
  - name: hetzner.hcloud
    # Python SDK also required — see requirements.txt

  - name: ansible.posix

  - name: community.general
