---
- name: Setup developer server
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - ../inventories/group_vars/all/vars.yml
    - ../inventories/group_vars/all/vault.yml
    - ../inventories/group_vars/hcloud_location/vars.yml
    - ../inventories/group_vars/hcloud_type/vars.yml

  vars:
    # Check `hcloud image list | grep ubuntu` for a list of available images.
    image: "ubuntu-24.04"
    hcloud_server_name: "{{ my_hetzner_config.name | default('my_hetzner_config.name must be configured in inventory/group_vars/all/vars.yml') }}"
    hcloud_server_group: "{{ my_hetzner_config.group | default('my_hetzner_config.group must be configured in inventory/group_vars/all/vars.yml') }}"
    hcloud_server_type: "{{ hcloud_default_type | default('hcloud_default_type must be specified') }}"
    hcloud_server_location: "{{ hcloud_default_location | default('hcloud_default_location must be specified') }}"
    hcloud_ssh_key_name: "{{ my_hetzner_config.ssh_key.name | default('my_hetzner_config.ssh_key.public_value must be configured in inventory/group_vars/all/vault.yml') }}"
    hcloud_token: "{{ my_hetzner_config.api_token | default('my_hetzner_config.api_token must be configured in inventory/group_vars/all/vault.yml') }}"

  tasks:
    - import_tasks: ../tasks/hetzner/ensure-ssh-key.yml

    - name: Create developer server
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        state: present
        name: "{{ hcloud_server_name }}"
        labels:
          platform: "linux"
        server_type: "{{ hcloud_server_type }}"
        image: "{{ image }}"
        location: "{{ hcloud_server_location }}"
        ssh_keys: "{{ hcloud_ssh_key_name }}"
      register: hcloud

    - name: Write hosts.ini with provisioned server IP
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/../inventories/hosts.ini"
        content: |
          [{{ hcloud_server_group }}]
          {{ hcloud_server_name }} ansible_host={{ hcloud.hcloud_server.ipv4_address }}

          [hcloud_type:children]
          {{ hcloud_server_group }}

    - name: Refresh inventory to ensure new host is available
      meta: refresh_inventory

    - import_tasks: ../tasks/add-server-to-known-hosts.yml
      vars:
        remote_ip: "{{ hcloud.hcloud_server.ipv4_address }}"