---
- name: Setup developer server
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - ../inventories/group_vars/all/vars.yml
    - ../inventories/group_vars/all/vault.yml
    - ../inventories/group_vars/hcloud_location/vars.yml
    - ../inventories/group_vars/hcloud_type/vars.yml

  vars:
    # Check `hcloud image list | grep ubuntu` for a list of available images.
    image: "ubuntu-24.04"
    hcloud_server_name: "{{ my_hetzner_config.name | default('my_hetzner_config.name must be configured in inventory/group_vars/all/vars.yml') }}"
    hcloud_server_group: "{{ my_hetzner_config.group | default('my_hetzner_config.group must be configured in inventory/group_vars/all/vars.yml') }}"
    hcloud_server_type: "{{ hcloud_default_type | default('hcloud_default_type must be specified') }}"
    hcloud_server_location: "{{ hcloud_default_location | default('hcloud_default_location must be specified') }}"
    hcloud_ssh_key_name: "{{ my_hetzner_config.ssh_key.name | default('my_hetzner_config.ssh_key.public_value must be configured in inventory/group_vars/all/vault.yml') }}"
    hcloud_token: "{{ my_hetzner_config.api_token | default('my_hetzner_config.api_token must be configured in inventory/group_vars/all/vault.yml') }}"

  tasks:
    - name: Ensure required variables are defined
      assert:
        that:
          - my_hetzner_config.api_token is defined
          - my_hetzner_config.api_token | length > 0
        fail_msg: "The environment variable HCLOUD_TOKEN must be defined"

    - name: Get local SSH key fingerprint
      ansible.builtin.command:
        cmd: "ssh-keygen -E md5 -lf ~/.ssh/{{ hcloud_ssh_key_name }}.pub"
      register: local_key_info
      changed_when: false

    - name: Set local key fingerprint fact
      ansible.builtin.set_fact:
        local_key_fingerprint: "{{ local_key_info.stdout.split()[1] | regex_replace('^MD5:', '') }}"

    - name: Gather existing Hetzner SSH keys
      hetzner.hcloud.ssh_key_info:
        api_token: "{{ hcloud_token }}"
      register: existing_ssh_keys

    - name: Upload SSH public key to Hetzner Cloud
      hetzner.hcloud.ssh_key:
        api_token: "{{ hcloud_token }}"
        state: present
        name: "{{ hcloud_ssh_key_name }}"
        public_key: "{{ lookup('file', '~/.ssh/' + hcloud_ssh_key_name + '.pub') }}"
      when: local_key_fingerprint not in (existing_ssh_keys.hcloud_ssh_key_info | map(attribute='fingerprint') | list)

    - name: Resolve SSH key name to use (existing or newly uploaded)
      ansible.builtin.set_fact:
        hcloud_ssh_key_name: >-
          {{ (existing_ssh_keys.hcloud_ssh_key_info
              | selectattr('fingerprint', 'equalto', local_key_fingerprint)
              | map(attribute='name')
              | list
              | first)
             if local_key_fingerprint in (existing_ssh_keys.hcloud_ssh_key_info | map(attribute='fingerprint') | list)
             else hcloud_ssh_key_name
          }}

    - name: Create developer server
      hetzner.hcloud.server:
        api_token: "{{ hcloud_token }}"
        state: present
        name: "{{ hcloud_server_name }}"
        labels:
          platform: "linux"
        server_type: "{{ hcloud_server_type }}"
        image: "{{ image }}"
        location: "{{ hcloud_server_location }}"
        ssh_keys: "{{ hcloud_ssh_key_name }}"
      register: hcloud

    - name: Write hosts.ini with provisioned server IP
      ansible.builtin.copy:
        dest: "{{ playbook_dir }}/../inventories/hosts.ini"
        content: |
          [{{ hcloud_server_group }}]
          {{ hcloud_server_name }} ansible_host={{ hcloud.hcloud_server.ipv4_address }}

          [hcloud_type:children]
          {{ hcloud_server_group }}

    - name: Refresh inventory to ensure new host is available
      meta: refresh_inventory

    - import_tasks: ../tasks/add-server-to-known-hosts.yml
      vars:
        remote_ip: "{{ hcloud.hcloud_server.ipv4_address }}"