---
- name: Update apt cache (if older than 1 hour)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - tree
      - unzip
      - python3-full
      - build-essential
      - libsecret-tools
      - seahorse
    state: present
  notify: Cleanup apt cache
